#!/usr/bin/env ruby

message_file = ARGV[0]
message = File.read(message_file)

$regex = /\A:.*:/

if !$regex.match(message)
  message = ":pencil: " + message
end

File.open(message_file, 'w') { |file| file.write(message) }